config/routes.rb
Rails.application.routes.draw do
  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout

   post "/run-game" => "games#update_game", as: :sendgame
   get "/run-game" => "games#get_game", as: :getgame

  resources :users, :sessions, :leader_boards, :games

  # You can have the root of your site routed with "root"
  root 'landing#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	belongs_to 		:game

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates	:first_name,			:presence			=> true,
						:length													=> {:maximum => 50}
	validates	:last_name,				:presence			=> true,
						:length													=> {:maximum => 50}
	validates	:email,						:presence			=> true,
						:format													=> {:with => email_regex},
						:uniqueness											=> {:case_sensitive => false}
	validates	:username,				:presence			=> true,
						:uniqueness											=> {:case_sensitive => false}
	validates :password,				:presence			=> true,
						:length													=> {:within => 8..40}

	before_save :encrypt_password

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)

		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	private
	def encrypt_password
		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
		self.encrypted_password = encrypt(password)
	end
	def encrypt(pass)
		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:create, :new]

  def new
  	@user = User.new
    render layout: 'session'
  end

  def create
  	@user = User.new(user_params)
    if @user.valid?
      if @user.save
        sign_in @user
        redirect_to @user, :flash => {notice: "Created the new user!"}
      else
        render layout: 'session', action: 'new'
      end
    else
      flash.alert = "Unable to create user!"
      render layout: 'session', action: 'new'
    end
  end

  def show
  	@user = User.find_by_id(params[:id])
    if @user.nil?
      redirect_to action: 'index', :flash => {:notice => "Error showing user"}
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    auth = User.authenticate(user_params[:email], user_params[:password])
    if !auth.nil?
      if @user.update(user_params)
        current_user = @user
        flash.alert = "Profile updated."
        redirect_to @user
      else
        flash.alert = "There was an error saving your profile"
        render 'edit'
      end
    else
      flash.alert = "You entered an incorrect password."
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(@current_user.id)
    if !@user.nil?
      @user.destroy
      sign_out
    else
      redirect_to @user, :flash => {:error => "An error occurred."}
    end
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :first_name, :last_name, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="row black-glass">
	<div class="col s3 center">
		<%= image_tag 'avatars/av01', :class => 'circle responsive-img' %>
		<p><b><%= @user.username %></b></p>
	</div>
	<div class="col s6">
	<h2>Edit Profile</h2>
		<%= form_for @user, url: {action: 'update'} do |f| %>
			<%= f.text_field :first_name, :placeholder => "First Name" %>
			<% if @user.errors.full_messages_for(:first_name).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:first_name).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.text_field :last_name, :placeholder => "Last Name" %>
			<% if @user.errors.full_messages_for(:last_name).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:last_name).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.text_field :email, :placeholder => "Email" %>
			<% if @user.errors.full_messages_for(:email).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:email).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.text_field :username, :placeholder => "Username" %>
			<% if @user.errors.full_messages_for(:username).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:username).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.password_field :password, :placeholder => "Password" %>
			<% if @user.errors.full_messages_for(:password).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:password).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.submit "Save Changes", :class => "btn waves-effect deep-orange darken-4" %>
			<%= link_to "Cancel", @user, :class => "btn waves-effect deep-orange darken-4" %>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
	<div class="col s8 offset-s2 black-glass">
	<h1>Sign Up</h1>
		<%= form_for @user, url: {action: 'create'} do |f| %>
			<%= f.text_field :first_name, :placeholder => "First Name" %>
			<% if @user.errors.full_messages_for(:first_name).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:first_name).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.text_field :last_name, :placeholder => "Last Name" %>
			<% if @user.errors.full_messages_for(:last_name).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:last_name).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.text_field :email, :placeholder => "Email" %>
			<% if @user.errors.full_messages_for(:email).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:email).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.text_field :username, :placeholder => "Username" %>
			<% if @user.errors.full_messages_for(:username).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:username).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.password_field :password, :placeholder => "Password" %>
			<% if @user.errors.full_messages_for(:password).first %>
				<div class="card card-panel red red-lighten-1">
					<% @user.errors.full_messages_for(:password).each do |error| %>
						<%= error %><br>
					<% end %>
				</div>
			<% end %>
			<%= f.submit "Create", :class => "btn waves-effect deep-orange darken-4" %>
		<% end %>
	</div>

app/views/users/show.html.erb
<div class="row user-glass">
	<div class="col s3 center">
		<%= image_tag 'avatars/av01', :class => 'circle responsive-img' %>
		<p><b><%= @user.username %></b></p>
	</div>
	<div class="col s7">
		<p>
			<span class="yText">Name:</span> <%=  @user.first_name %>&nbsp;<%= @user.last_name %><br>
			<span class="yText">Email:</span> <%= @user.email %><br>
			<span class="yText">User ID:</span> <%= @user.id%><br>
			<span class="yText">Record (W/L):</span> <%= @user.wins.nil? ? 0 : @user.wins %>/<%= @user.losses.nil? ? 0 : @user.losses %>

		</p>
		<% if @user.id == @current_user.id %>
		<%= link_to "Start Game", new_game_path, :class => "btn waves-affect deep-orange darken-4" %> &nbsp;
		<%= link_to "Edit Profile", edit_user_path, :class => "btn waves-affect deep-orange darken-4" %> <br><br>
		<%= button_to "Remove Account", @user, :method => :delete, :class => "btn waves-affect deep-orange darken-4" %>		
		<% end %>
	</div>
</div>

		