config/routes.rb
Rails.application.routes.draw do
  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout

   post "/run-game" => "games#update_game", as: :sendgame
   get "/run-game" => "games#get_game", as: :getgame

  resources :users, :sessions, :leader_boards, :games

  # You can have the root of your site routed with "root"
  root 'landing#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="page-footer grey darken-4">
	
	<div class="row">
		<%= image_tag 'hl_logo_sm', :style => 'vertical-align: middle	' %>
	</div>
	
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
  <ul id="dropdown1" class="dropdown-content grey darken-3">
    <li><%= link_to "Profile", @current_user, :class => 'yellow-text' %></li>
    <li class="divider"></li>
    <li><%= link_to "Log Out", logout_path, :class => 'yellow-text' %></li>
  </ul>
	<nav>
		<div class="nav-wrapper grey darken-4">
      <%= link_to(image_tag("ol_logo",:style => 'max-height: 80%; vertical-align: middle;'), root_path) %> 
  		<ul class="right hide-on-med-and-down">
        <li><%= link_to "Start Game", new_game_path %></li>
        <li><%= link_to "Leader Boards", leader_boards_path %></li>
        <li>
          <a class="dropdown-button" href="#" data-activates="dropdown1">
          <%= @current_user.first_name %> <%= @current_user.last_name %><i class="mdi-navigation-arrow-drop-down right"></i>
          </a>
        </li>
  		</ul>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<main>
		<div class="container">
			<div class="row">
				<div class="col s12">
					<div class="row">
						<div class="col s6 offset-s3 center-align">
							<% flash.each do |key, value| %>
								<% if key == "alert" %>
									<div class="card-panel red red-lighten-1"><%= value %></div>
								<% elsif key == "notice" %>
									<div class="card-panel blue blue-lighten-1"><%= value %></div>
								<% end %>
	      					<% end %>
						</div>
					</div>
					<!-- CONTENT GOES HERE -->
					<!-- EACH PAGE NEEDS TO BE WRAPPED IN A ROW -->
					<%= yield %>
				</div>
			</div>
		</div>
	</main>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/game.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<main>
		<div class="container-fluid">
			<div class="row">
				<div class="col s12">
					<div class="row">
						<div class="col s6 offset-s3 center-align">
							<% flash.each do |key, value| %>
								<% if key == "alert" %>
									<div class="card-panel red red-lighten-1"><%= value %></div>
								<% elsif key == "notice" %>
									<div class="card-panel blue blue-lighten-1"><%= value %></div>
								<% end %>
	      					<% end %>
						</div>
					</div>
					<!-- CONTENT GOES HERE -->
					<!-- EACH PAGE NEEDS TO BE WRAPPED IN A ROW -->
					<%= yield %>
				</div>
			</div>
		</div>
	</main>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col s12">
				<div class="row">
					<div class="col s6 offset-s3 center-align">
						<% flash.each do |key, value| %>
							<% if key == "alert" %>
								<div class="card-panel red red-lighten-1"><%= value %></div>
							<% elsif key == "notice" %>
								<div class="card-panel blue blue-lighten-1"><%= value %></div>
							<% end %>
      					<% end %>
					</div>
				</div>
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>